name: Documentation Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci || echo "No package.json found"
          # Install documentation tools if needed
          npm install -g mkdocs-material || echo "MkDocs not needed"
        continue-on-error: true
      
      - name: Build documentation
        run: |
          echo "Building documentation..."
          
          # Ensure site directory exists
          mkdir -p site
          
          # Try different documentation tools
          if [ -f "mkdocs.yml" ]; then
            mkdocs build || echo "MkDocs build failed, using default"
          elif [ -f "docsify.json" ]; then
            echo "Docsify documentation"
          elif [ -f "package.json" ]; then
            npm run docs:build || echo "No docs build script"
          fi
          
          # Create default documentation if site is empty
          if [ ! -f "site/index.html" ]; then
            cat > site/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Project Documentation</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>Project Documentation</h1>
    <p>Documentation is being generated...</p>
</body>
</html>
EOF
          fi
      
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
          if-no-files-found: error
          retention-days: 30
  
  deploy-docs:
    name: Deploy to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: ./site
          if-no-files-found: error
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
      - name: Deployment summary
        run: |
          echo "## Documentation Deployment" >> $GITHUB_STEP_SUMMARY
          echo "- Status: Success" >> $GITHUB_STEP_SUMMARY
          echo "- URL: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Deployed at: $(date)" >> $GITHUB_STEP_SUMMARY

