name: Documentation Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            if [ -f "package-lock.json" ] || [ -f "npm-shrinkwrap.json" ] || [ -f "yarn.lock" ]; then
              npm ci || echo "npm ci failed"
            else
              npm install || echo "npm install failed"
            fi
          else
            echo "No package.json found"
          fi
          # Install documentation tools if needed
          npm install -g mkdocs-material || echo "MkDocs not needed"
        continue-on-error: true
      
      - name: Build documentation
        run: |
          echo "Building documentation..."
          
          # Ensure site directory exists
          mkdir -p site
          
          # Try different documentation tools
          if [ -f "mkdocs.yml" ]; then
            mkdocs build || echo "MkDocs build failed, using default"
          elif [ -f "docsify.json" ]; then
            echo "Docsify documentation"
          elif [ -f "package.json" ]; then
            npm run docs:build || echo "No docs build script"
          fi
          
          # Create default documentation if site is empty
          if [ ! -f "site/index.html" ]; then
            cat > site/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Project Documentation</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>Project Documentation</h1>
    <p>Documentation is being generated...</p>
</body>
</html>
EOF
          fi
      
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
          if-no-files-found: error
          retention-days: 30
  
  # Docs deployment disabled (using Vercel or no Pages)
  # To re-enable, restore a deployment job here.

