name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Test step
      run: |
        echo "✅ Test workflow is working!"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        
    - name: List files
      run: |
        echo "📁 Repository contents:"
        ls -la
        echo ""
        echo "📁 Workflows directory:"
        ls -la .github/workflows/
